default: &default
  adapter: postgresql
  pool: 5
  database: ruby_gem
  username: postgres
  password: root
  timeout: 5000
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
