default: &default
  adapter:  <%= ENV['DATABASE_ADAPTER'] %>
  encoding: <%= ENV['DATABASE_ENCODING'] %>
  pool:     <%= ENV['DATABASE_POOL'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATEBASE_PASSWORD'] %>
  host:     <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default

test:
  <<: *default
  database: ruby_gem_test

production:
  <<: *default
